### ISSUE TITLE
Интерфейс

### ISSUE THREAD

**Issue by lavrenkov-sketch** [sledopyt8/tracker_statuses#1]
Здравствуйте, есть возможность убрать ui чтобы сделать программу более универсальной?

**Comment by dhw-design** [comment]
Здравствуйте. Имеется в виду сделать консольный вариант утилиты? В принципе такое возможно. Для расшифровки, например, можно будет вводить данные в формате <название параметра>=<значение параметра>. И утилита будет выводить расшифровку это параметра

**Comment by dhw-design** [comment]
> 
> 
> Здравствуйте, есть возможность убрать ui чтобы сделать программу более универсальной?
Здравствуйте. Имеется в виду сделать консольный вариант утилиты? В принципе такое возможно. Для расшифровки, например, можно будет вводить данные в формате <название параметра>=<значение параметра>. И утилита будет выводить расшифровку это параметра

**Comment by lavrenkov-sketch** [comment]
Интересует возможность создания консольного,асинхронного демона для работы с трекерами по TCP сокету

**Comment by dhw-design** [comment]
> 
> 
> Интересует возможность создания консольного,асинхронного демона для работы с трекерами по TCP сокету

Практическая каждая фирма-производитель использует свой оригинальный протокол передачи поверх TCP или UDP соединения. И если делать демона, то нужно сначала определиться с поддерживаемым оборудованием, протоколом. Это с одной стороны, что бы данные принять от трекера. С другой стороны, эти данные нужно или куда-нибудь дальше отправить или сохранить на диск, например, в базу данных.

А данная программа напрямую с трекерами не общается, а делает только расшифровку некоторых параметров, отправляемых на сервер. Причем значения этих параметров вводятся вручную.
